NETWORK_PASSPHRASE="Public Global Stellar Network ; September 2015"

ACCOUNTS=["GATJBF36ZGL6TGYGSLA5RJO6KTRERLQJDCCSOS2O7IQS6MOGF52MTHSZ",
]
VERSION="2.0.0"

[DOCUMENTATION]
ORG_NAME="BioRes"
ORG_URL="https://biorslab.com/"
ORG_DESCRIPTION="We want BioRs to become the most widely used form of digital payment. In order to achieve mass adoption of crypto we believe that a coin must have the most common utility and real world to buy physical goods and items."
ORG_TWITTER="@BioRsLab"
ORG_LOGO="https://gcdn.pbrd.co/images/rFHEyzKYQGWF.png"
ORG_OFFICIAL_EMAIL="https://biorslab.com/"



[[CURRENCIES]]
code="BioRes"
issuer="GATJBF36ZGL6TGYGSLA5RJO6KTRERLQJDCCSOS2O7IQS6MOGF52MTHSZ"
anchor_asset_type="crypto"
anchor_asset="false"
name="BioRes"
desc="BioRs is the heart of Innovative Bioresearch ecosystem"
image="https://gcdn.pbrd.co/images/rFHEyzKYQGWF.png"
fixed_number=500000
max_number=500000
is_unlimited=false
#BioRes was issued using the open and inclusive Stellar blockchain network.
